    "apple": [
      "5",
      "5c",
      "5s",
      "6",
      "6 plus",
      "6s",
      "6s plus",
      "7",
      "7 plus",
      "8",
      "8 plus",
      "se",
      "se 2",
      "se 3",
      "x",
      "xr",
      "xs",
      "xs max",
      "11",
      "11 pro",
      "11 pro max",
      "12",
      "12 mini",
      "12 pro",
      "12 pro max",
      "13",
      "13 mini",
      "13 pro",
      "13 pro max",
      "14",
      "14 mini",
      "14 pro",
      "14 pro max",
      "15",
      "15 plus",
      "15 pro",
      "15 pro max",
      "16",
      "16e",
      "16 plus",
      "16 pro",
      "16 pro max"
      